return {
	Nodes = {
		OwnerTerminalGiven = {
			Name = "Owner",
			Portrait = "rbxassetid://15603749034",
			VoiceId = "7",
			Pitch = -6,
			Speed = 1,
			Volume = 3,
			Dialogue = "Stuck? tough luck.<br/>(<b>Tweet Or Xeet.I Called Someone A Literal Trotter</b>)",
			Responses = {
				{
					Text = "A what..?",
					Type = "Close",
				},
				{
					Text = "...",
					Type = "Close",
				},
			},
		},
	},
}
