return {

	Nodes = {
		CashierNoTalk = {
			Name = "Shayden",
			Portrait = "rbxassetid://14875151473",
			Dialogue = "Why are you still here?<br/>Store policy is to not interfere anyway, or i'll be fired for being the hero.",
			VoiceId = 6,
			Pitch = 12,
			Speed = 1,
			Volume = 1,
			PlayTheme = "StoreBackground",
			Responses = {
				{
					Text = "IT WAS A MISINPUT! CALM DOWN!",
					Type = "Close",
				},
				{
					Text = "SEEYAWANNABEYA!",
					Type = "Close",
				},
			},
		},
	},
}
