return {
	Nodes = {
		PsychoMantisFail = {
			Name = "?????? ???",
			Portrait = "rbxassetid://7129644829",
			Dialogue = "... You won right?",
			VoiceId = 1,
			Pitch = 12,
			Speed = 0.5,
			Volume = 1,
			PlayTheme = "Calm",
			Responses = {
				{
					Text = "How do you know my name..?",
					Type = "NextMessage",
					NextId = "One",
				},
				{
					Text = "(RUN)",
					Type = "Close",
				},
			},
		},
	},
}
