return {
	Nodes = {
		SafechatterAccepted = {
			Name = "Guest",
			Portrait = "rbxassetid://60376597",
			Dialogue = "I can only see menu chats.",
			VoiceId = "10",
			Pitch = 1,
			Speed = 1,
			Volume = 1,
			PlayTheme = "GuestTheme",
			Responses = {
				{
					Text = "............................",
					Type = "Close",
				},
				{
					Text = "# #### #### ###",
					Type = "Close",
				},
			},
		},
	},
}
