return {
	Nodes = {
		PsychoMantisAccepted = {
			Name = "Hacker Ham",
			Portrait = "rbxassetid://16642438470",
			Dialogue = "Where's my keyboard? Hello K- I mean I saw you finish the competition!",
			PlayTheme = "Calm",
			Responses = {
				{
					Text = "Err forgot to claim oops",
					Type = "Close",
				},
				{
					Text = "I'm on XBOX, I can't speak!",
					Type = "Close",
				},
			},
		},
	},
}
