return {
	Nodes = {
		ThiefAccepted = {
			Name = "Dan Foe",
			Portrait = "rbxassetid://10851325055",
			Dialogue = "DUNNO WHAT I WAS FINKIN LEEAVIN THAT TV BEHAIIND...",
			VoiceId = "5",
			Pitch = -1,
			Speed = 1,
			Volume = 3,
			PlayTheme = "Aerobics",
			Responses = {
				{
					Text = "...Jesus christ almighty.",
					Type = "Close",
				},
				{
					Text = "...",
					Type = "Close",
				},
			},
		},
	},
}
