local CustomPsychoMantisDialogue = {}

CustomPsychoMantisDialogue[1359573625] =
	"I see you like Deepwoken huh? Last I played I was farming the Primadon whilst a bush camper spawned in and snagged the chests. Interesting though, very interesting.."

CustomPsychoMantisDialogue[17625359962] =
	"A fan of RIVALS are we? A little sniper merchant every time you play the Crossroads map huh? INTERESTING... "

CustomPsychoMantisDialogue[126884695634066] =
	"I see you like growing gardens, would be a shame if I wiped your data and your Ultra-Wet-Black-Peppercorn-Texas-Style Plant huh? just joking... Shi-lu-lu-lu-lu (interesting)"

CustomPsychoMantisDialogue[4588604953] =
	"Oh dear, a Criminality lover are we? Thuggin' around Armory 2? Hanging out in groups of 10 to assert dominance? Interesting..."

CustomPsychoMantisDialogue[109983668079237] =
	"I see you like stealing brainrots..? I would steal your brain but it's rotting or empty. Just joking. Gyah hah harr hee gee haaaah. Interesting though, very interesting."

CustomPsychoMantisDialogue[18668065416] =
	"Blue Lock lover are we? Not upping your ball knowledge instead of focusing on the bootleg Shaolin Soccer movie? Interesting."

CustomPsychoMantisDialogue[18687417158] =
	"A Forsaken enthusiast huh? The spawn point of these so called 'retrosloppers' with DBD gameplay, interesting, very interesting..."

CustomPsychoMantisDialogue[99567941238278] =
	"An Ink Game lover eh? Hope you're not pushing, tripping or grabbing people... Maybe a permanent red light game will be there if so..."

return CustomPsychoMantisDialogue
